### ISSUE TITLE
Question: Download zip straight to folder, not its own folder.

### ISSUE THREAD

**Issue by Runisco** [MandoCoding/ForumAttachmentScript#7] opened 2021-11-29 10:09 UTC
Is there a piece of code to change that allows the zip to be straight to the title folder, instead of being put into its own folder? 

So instead of threadtitle/144/zip
you get
threadtitle/zip?

**Comment by MandoCoding** [comment] 2021-12-02 18:32
This is being investigated at the moment, the problem is the inclusion of cyberdrop and bunkr albums which will lead to mixed folders. I'd like to try getting proper album names and then moving everything to one level as before

**Comment by MandoCoding** [comment] 2021-12-04 01:51
Resolved with 1.4.5

**Closed by MandoCoding** 2021-12-04 01:51 UTC
Labels: enhancement
